<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_yes_button</name>
   <tag></tag>
   <elementGuidId>5507ba49-75ca-46b6-9f25-a0cdd0d797de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//roma-delete-by-selection-modal/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
