<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>more_options_button</name>
   <tag></tag>
   <elementGuidId>4cbecd08-7ed2-414f-8ec6-aece2d5f29ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//roma-show-budget/div[1]/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
