<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre de tu negocio_name</name>
   <tag></tag>
   <elementGuidId>f5ad5c86-5e2e-4de3-955f-cdda2a967284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyContainer']/roma-mf-online-booking/mf-online-booking/div/div/div/div/form/div/div/div/div/div[2]/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;name&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5afe2bc6-3656-46c0-a083-0d3d5a9abdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f0cfa63-09b6-4d54-ab03-8654a92c5716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresar nombre</value>
      <webElementGuid>a0429f7d-2364-4743-ae0a-5c2d7a611143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>38d81242-f1b0-4bfe-a27f-bd170bc81504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>927633eb-ffca-47b0-b707-f7a2bde022ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 border-primary-100</value>
      <webElementGuid>554575b2-4ae9-4078-9461-14c73f1b6510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name&quot;)</value>
      <webElementGuid>301070e1-a3cd-4048-aa32-bd7ae05b64f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name']</value>
      <webElementGuid>670fef6e-6b11-4c5f-bfba-1f16981cac0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/roma-mf-online-booking/mf-online-booking/div/div/div/div/form/div/div/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>c65af67b-aa0d-4c6c-acca-9840d3a49439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>da2ae668-ad41-4cb6-85d1-d0bc57798a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ingresar nombre' and @id = 'name']</value>
      <webElementGuid>3d1fad64-93ec-4d2b-956c-ce4bcf28c90e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
