<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_booking.taclia.com_url</name>
   <tag></tag>
   <elementGuidId>34e4f137-02a6-4ea8-8fe5-a8a671e7a97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyContainer']/roma-mf-online-booking/mf-online-booking/div/div/div/div/form/div/div/div/div/div[2]/div/div[2]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;url&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3c6707f-16b2-4bdf-a78f-f3adb2fdeb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa588ff6-c239-4088-84fc-b9790605a167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa el texto del enlace</value>
      <webElementGuid>ff05fbf5-7aa8-4484-9fee-462f58a88225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>73771a3d-cb22-4e94-9f18-1e473855ec76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>e695ac82-d681-4005-adaf-e89aa1ad3e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 border-primary-100</value>
      <webElementGuid>d57f74a9-b227-43cc-a146-ead1da264874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>e954a12c-838c-455a-aacb-285e694da44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;url&quot;)</value>
      <webElementGuid>773ea9fe-3bd9-4fbd-a441-31652819e9ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='url']</value>
      <webElementGuid>4481b98b-7a1b-4fbc-81a9-32a27d7638f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/roma-mf-online-booking/mf-online-booking/div/div/div/div/form/div/div/div/div/div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>9e7f60db-2279-46ad-a546-637d22746048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>bc3826d7-d705-4969-b340-396100ffde09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ingresa el texto del enlace' and @id = 'url']</value>
      <webElementGuid>2bf365de-83f3-4c18-bd51-65645ebc6718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
