<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar</name>
   <tag></tag>
   <elementGuidId>032d119d-efbb-4947-b615-dacaa7bbee3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//roma-create-final-v2/div[2]/div[2]/roma-final-wrapper-detail/div[1]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.footer-button.roma-button.save-btn.user-feature.is-user-available.is-checkable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Guardar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12eec3ea-2e95-4c50-af70-be9cf4fd2387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>493f7288-b60e-4dca-8648-7d3b506931d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79590d92-0ed4-4739-b3fa-45eccb9035d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-button roma-button save-btn user-feature is-user-available is-checkable</value>
      <webElementGuid>d051b373-3158-4963-a0a3-83606197de4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Guardar </value>
      <webElementGuid>4a2b5d59-987c-4b60-ac51-3fd859d0e1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/roma-create-final-v2[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal__body safe-area-padding&quot;]/div[@class=&quot;modal__body__content&quot;]/roma-final-wrapper-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper__body&quot;]/div[@class=&quot;wrapper__body__footer&quot;]/button[@class=&quot;footer-button roma-button save-btn user-feature is-user-available is-checkable&quot;]</value>
      <webElementGuid>1aaa5c88-50e0-4b62-acad-2385f5db9669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>588338c7-b82f-4146-a449-5d0042aeeb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/roma-create-final-v2/div[2]/div[2]/roma-final-wrapper-detail/div/div[2]/button</value>
      <webElementGuid>85dbeb27-1122-43ac-a23d-530b8f9bb85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir a campos personalizados'])[1]/following::button[1]</value>
      <webElementGuid>b87a3850-f74c-4379-92a9-6349cc92d3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='campos personalizados'])[1]/following::button[1]</value>
      <webElementGuid>20084858-400a-4a82-942a-c3768db7d8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archivos adjuntos'])[1]/preceding::button[1]</value>
      <webElementGuid>67685383-73c4-494d-842f-58566ce42a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamaño máximo de archivo 10 MB'])[1]/preceding::button[1]</value>
      <webElementGuid>b8b23d79-cf05-4837-b9c6-fa27284d8366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar']/parent::*</value>
      <webElementGuid>023f55e6-516b-4a90-a758-240f1cfa8b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roma-final-wrapper-detail/div/div[2]/button</value>
      <webElementGuid>6e7ffdb8-366c-4987-a4b8-fc419a03e690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Guardar ' or . = ' Guardar ')]</value>
      <webElementGuid>dc05415f-fdb4-4fb4-89c2-5ecfaea2c3f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
