<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NMERO FISCAL_form-control md-input ng_40ba76</name>
   <tag></tag>
   <elementGuidId>dbdc1ba9-49ae-4b29-8104-de3e72be0966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.md-input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresar Número Fiscal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c54b5bba-b51b-4176-823f-84b721e3b063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fb851e1-7e35-4dae-927d-b6b46e81387d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nif</value>
      <webElementGuid>d2b1466c-2b45-43a3-ab1a-79b02fbe9bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>45b65899-0770-48cb-9890-ee7407ed065c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control md-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3525856b-20ac-49f7-b64c-b8f282a13b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresar Número Fiscal</value>
      <webElementGuid>bf0deba1-b18a-4adc-b248-2429f7bfb783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/roma-create-final-v2[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal__body safe-area-padding&quot;]/div[@class=&quot;modal__body__content&quot;]/roma-final-wrapper-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper__body&quot;]/div[@class=&quot;wrapper__body__content&quot;]/form[@class=&quot;ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;wrapper__body__content__field&quot;]/div[@class=&quot;wrapper__body__content__field__content wrapper-pro-feature-user is-user-available&quot;]/input[@class=&quot;form-control md-input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>459055fd-53b0-4afe-975b-77a673bdb236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>27152ccf-eb12-4fb1-87ad-c68029b3345e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/roma-create-final-v2/div[2]/div[2]/roma-final-wrapper-detail/div/div/form/div[4]/div[2]/input</value>
      <webElementGuid>491e6559-31a9-468b-bd27-3a2c7412adec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>b1456b11-1dda-4f6b-8d8b-fe90d648c2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ingresar Número Fiscal']</value>
      <webElementGuid>cdf531b7-4bab-4c97-b1cb-ec89c31d874f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
