<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telfono_tel</name>
   <tag></tag>
   <elementGuidId>093aa2d4-c580-4f60-b44e-a7ab0e60658c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tel&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresa un teléfono&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0d9c225-5a66-48fb-b4e4-6236ced7d734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2a6e7cee-5008-4ad0-a8be-d695c89c2919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>00ac4fba-b9a9-4cac-8c7a-c1642bea608d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxdecimals</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a08680c2-6270-467c-9d26-dc6896dfca24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4da50c41-9a9c-4f19-8f04-b9e19141eebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d17eb9f2-4df0-4dec-86a6-140210d11c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>41051e9b-c09b-4b68-b7a9-b48d94a9df58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone__input placeholderBlue</value>
      <webElementGuid>4eb6842f-508d-41cf-a96c-497a1bd90f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa un teléfono</value>
      <webElementGuid>cf67440e-58b2-4967-8089-11528d387bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/roma-root[1]/roma-new-register[1]/div[@class=&quot;new-register&quot;]/div[@class=&quot;modal-register&quot;]/form[@class=&quot;form-register ng-untouched ng-dirty ng-invalid&quot;]/div[@class=&quot;mb-3 email-input&quot;]/roma-rm-phone-select-input[1]/div[@class=&quot;phone__select__wrapper&quot;]/div[@class=&quot;input__wrapper&quot;]/div[@class=&quot;phone__wrapper&quot;]/input[@class=&quot;phone__input placeholderBlue&quot;]</value>
      <webElementGuid>869fe2f3-bbb3-4d77-ac9a-27dec69b35fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tel']</value>
      <webElementGuid>14cf94c6-6133-4454-9c63-da79f38dc514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>255a5375-47fa-49ca-8239-96498492b106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'tel' and @placeholder = 'Ingresa un teléfono']</value>
      <webElementGuid>6f29c3d8-9793-4c55-8036-3555a9c9e887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
