<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_0000</name>
   <tag></tag>
   <elementGuidId>5f223dd1-de07-47ef-8dd7-219e052ec240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the time of your booking'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;00:00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2945b23c-ee7a-4757-8942-4625fee2a896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tag  w-[70px]</value>
      <webElementGuid>233a446d-aa57-49bf-83d3-0f34e1d860cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00:00</value>
      <webElementGuid>a600b2c4-5cac-44df-a465-f13eaa5decb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;full-modal&quot;]/div[@class=&quot;full-modal-body&quot;]/div[@class=&quot;flex justify-between flex-row w-full&quot;]/div[@class=&quot;w-full md:w-[65%]&quot;]/div[@class=&quot;flex flex-col max-w-[600px] w-full&quot;]/div[@class=&quot;w-full flex flex-wrap gap-3 xs:gap-4&quot;]/button[@class=&quot;tag  w-[70px]&quot;]</value>
      <webElementGuid>963e3e56-1543-48e0-a753-5a8967f0a958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the time of your booking'])[1]/following::button[1]</value>
      <webElementGuid>fbd201a5-900c-42ea-a382-8c13bb24cc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tu'])[1]/following::button[43]</value>
      <webElementGuid>0586b4e7-de93-428d-b10c-fc76597f091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testob5'])[3]/preceding::button[48]</value>
      <webElementGuid>e91e52c2-bdc7-4c24-a7ab-399264e5d803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0'])[9]/preceding::button[48]</value>
      <webElementGuid>e8052539-8c9a-41bc-9201-e53dc756ad13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00:00']/parent::*</value>
      <webElementGuid>1952ba2b-8c85-44be-aa12-4c2bfd592187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>4bcb8681-2f74-47e0-9a36-7b0c55e20105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '00:00' or . = '00:00')]</value>
      <webElementGuid>b10dd238-e985-48d8-8cc6-a90dcc1e21a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
