<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin (slo para servicios a domici_bb55a9</name>
   <tag></tag>
   <elementGuidId>5c95c104-f90e-461f-8e9c-3fd4a1ccfde2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingresar dirección&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1e5034e-3225-4742-a15f-1c09a24ea855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>970997b3-7625-4de3-b044-8161c159cd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-input</value>
      <webElementGuid>8f6530eb-0b6b-4d71-85cd-331a938b72e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresar dirección</value>
      <webElementGuid>f79f6088-6afd-475a-8850-6058c3f158cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c81d636a-d26c-4bf0-b272-55f9bd88763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-input&quot;)</value>
      <webElementGuid>5be67b08-5380-4fd9-84f2-46319abbee17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address-input']</value>
      <webElementGuid>a338cd0b-a321-4240-9aca-50f1487fc76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>7d307f6c-5bcb-436a-8333-72e233bff0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'address' and @id = 'address-input' and @placeholder = 'Ingresar dirección']</value>
      <webElementGuid>dbfc4df5-3887-4865-93c3-698ebf335839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
