<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text</name>
   <tag></tag>
   <elementGuidId>04d4a655-9172-47e9-af86-79d2e426ac2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-input-prefix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-input-prefix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;+00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9320213b-91b0-42f6-bc6e-5240e405b8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-prefix input-error</value>
      <webElementGuid>11e4c25b-310f-4289-a9dc-f07e3df2faed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6074df9-0bcf-4050-8a55-5108365dc2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone-prefix</value>
      <webElementGuid>e769cac2-f56d-4480-91d3-06f07844d743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-input-prefix</value>
      <webElementGuid>fe9c9a8d-8401-4b46-9780-b19f17f82bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+00</value>
      <webElementGuid>edf4c8e0-0c16-4b32-bc08-bbbc7f30028e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4b1b4ec8-257b-4c3a-925e-5ee0b0d63af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-input-prefix&quot;)</value>
      <webElementGuid>515665bc-972a-4702-8da5-3891cdacd9d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-input-prefix']</value>
      <webElementGuid>d83b110e-df71-4b5b-ba17-3f35754bb4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>21f28798-9423-4cdf-87b3-9fb3e84e934c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[(text() = 'text' or . = 'text') and @name = 'phone-prefix' and @id = 'phone-input-prefix' and @placeholder = '+00']</value>
      <webElementGuid>9c281717-872f-4a9a-b78c-7e5e7017362d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
