<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0_custom-radio</name>
   <tag></tag>
   <elementGuidId>1e8e4ae3-5abb-4e49-9c8d-39ba04a14fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.custom-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div[2]/div[2]/div[2]/div/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.custom-radio >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7c212c3-8caa-47db-8392-a0e69bf55118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-radio</value>
      <webElementGuid>50799846-f275-4648-ba68-605ffeacf451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;w-full lg:w-5/6 mx-auto py-10 min-h-[80vh]&quot;]/div[@class=&quot;w-full px-10 lg:w-3/5 mb-20&quot;]/div[@class=&quot;flex flex-col items-start gap-4 relative&quot;]/div[@class=&quot;flex-col gap-2 pl-2 flex items-start relative self-stretch w-full&quot;]/div[@class=&quot;flex flex-col gap-2 relative w-full&quot;]/div[@class=&quot;flex items-start justify-between text-black&quot;]/label[@class=&quot;radio-label&quot;]/span[@class=&quot;custom-radio&quot;]</value>
      <webElementGuid>054b4bd1-78fd-44b7-8c3f-f8d0a0153fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/div[2]/div[2]/div/label/span[2]</value>
      <webElementGuid>fa43328b-6dab-4f2b-8cd1-82f3aeecf303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>dd27c6ae-d838-4bc4-8f6f-28958e906f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/div[2]/div[4]/div/label/span[2]</value>
      <webElementGuid>7ef6cad5-2ace-4670-9699-667683d90413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/span[2]</value>
      <webElementGuid>35d643aa-56ac-4eb7-b594-e4475c585363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
