<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Gestion interna_slider-large round</name>
   <tag></tag>
   <elementGuidId>4277dcef-4849-4fe2-8aef-7559599a1d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/roma-root/roma-admin/div/div[2]/div[2]/div/roma-company-modules/div[2]/div/div[1]/div/div/div[1]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slider-large.round</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.slider-large >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>838c0ed9-8bf7-47fe-8733-391465842843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-large round</value>
      <webElementGuid>645b6ae6-cd46-4f73-afb2-13b843ed62c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyContainer&quot;)/roma-company-modules[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;register_container wrapper-pro-feature-user is-user-available&quot;]/div[@class=&quot;form-functions&quot;]/div[@class=&quot;form-functions-card gestion-interna&quot;]/div[@class=&quot;module-card&quot;]/div[@class=&quot;module-content&quot;]/div[@class=&quot;module-content-option-title&quot;]/label[@class=&quot;switch-large custom-tooltip bottom&quot;]/span[@class=&quot;slider-large round&quot;]</value>
      <webElementGuid>4bfd90ba-a5b8-46ed-b5b4-14c372669a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/roma-company-modules/div[2]/div/div/div/div/div/label/span</value>
      <webElementGuid>7aa33025-5a35-4e88-b483-ee53ff1abe02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>1c84d9a4-9347-4136-a0ea-d9afa35b5365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
