<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Empezar</name>
   <tag></tag>
   <elementGuidId>58932838-3356-4300-a436-1b9ea57f43db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Empezar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09bbd55c-bd35-47fc-8476-0528743e8735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>08b9cd93-23b7-4c9b-9bce-57723f241b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-register</value>
      <webElementGuid>ecb2a103-591b-48ab-9b99-00d86b4a723d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Empezar </value>
      <webElementGuid>ef693fb1-46d7-46b2-90ea-07cb7bff4514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/roma-root[1]/roma-new-register[1]/div[@class=&quot;new-register&quot;]/div[@class=&quot;modal-register&quot;]/div[@class=&quot;steps&quot;]/div[1]/form[@class=&quot;form-desktop ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;register-footer&quot;]/div[@class=&quot;footer-button button-next button-next-step-two&quot;]/div[@class=&quot;custom-tooltip top&quot;]/button[@class=&quot;button-register&quot;]</value>
      <webElementGuid>4a1fa439-5776-4857-8f15-e821a6048af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>aa74c6b3-0d15-42ab-9c09-a415f35ee888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debes escoger una de las opciones para empezar.'])[1]/following::button[1]</value>
      <webElementGuid>421308ef-9045-4473-98c8-ad9998dd4b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='de 2'])[1]/following::button[1]</value>
      <webElementGuid>1888fe80-ca66-45b9-927c-f5b5905d9965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::button[1]</value>
      <webElementGuid>ddfc1f13-6d21-4a39-b1f4-a1d2184b938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Empezar']/parent::*</value>
      <webElementGuid>7b2c5174-f2ae-49ec-96b6-17877de6262a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/button</value>
      <webElementGuid>98c39ff2-ae71-4fff-9f3d-a0f460375d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Empezar ' or . = ' Empezar ')]</value>
      <webElementGuid>ceda6fbb-f0ca-475f-ba02-32db31afd1b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
