<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mis fichajes</name>
   <tag></tag>
   <elementGuidId>a9f26790-9755-4b13-941d-79ce7a7ce137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-2']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-focus-indicator.button-sidebar-dropdown.mat-menu-item.user-feature-hide.is-user-available.is-checkable.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Mis fichajes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd4b75da-0195-469c-ad56-884537c38f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator button-sidebar-dropdown mat-menu-item user-feature-hide is-user-available is-checkable cdk-focused cdk-mouse-focused</value>
      <webElementGuid>6d1886ce-4a36-4692-ac45-73d63682912a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>9b1fa6bf-ec8f-42b9-b67b-f98d9e0011d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d850a93-fd65-49c5-8feb-f2a630ef35d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>830929dc-b89f-406a-923c-52aa437bbcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/clock-hours</value>
      <webElementGuid>956d83cc-f095-437e-8d9a-a9c1c7a77927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mis fichajes</value>
      <webElementGuid>6a7acfb8-e3d8-4bb7-a70c-c94d77182968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c160-7&quot;]/div[@class=&quot;sidebar-dropdown-wrapper ng-tns-c160-7&quot;]/a[@class=&quot;mat-focus-indicator button-sidebar-dropdown mat-menu-item user-feature-hide is-user-available is-checkable cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>b564b73d-84af-4825-86d0-2673f95fba62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div[2]/a</value>
      <webElementGuid>67c319ef-4318-44a4-a1f5-967cd5c865b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control horario'])[1]/following::a[1]</value>
      <webElementGuid>7ff2774c-363b-4137-87ee-7fcb65379d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestión interna'])[1]/following::a[1]</value>
      <webElementGuid>220bf4fe-78d0-4b26-8761-050dea945456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis ausencias'])[1]/preceding::a[1]</value>
      <webElementGuid>af459c0a-1227-4494-8295-f1b4e95de4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/clock-hours')]</value>
      <webElementGuid>f2039e5d-c888-4ba2-bbb0-0178bb1532b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/mat-expansion-panel/div/div/div[2]/a</value>
      <webElementGuid>38a755ca-911b-4aaf-afda-c3adc02cdb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/clock-hours' and (text() = 'Mis fichajes' or . = 'Mis fichajes')]</value>
      <webElementGuid>eae9f26b-0c99-4972-802c-0ccf0b18d915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
