<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mis fichajes</name>
   <tag></tag>
   <elementGuidId>a9f26790-9755-4b13-941d-79ce7a7ce137</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/roma-root/roma-admin/div/div[1]/roma-sidebar/div[1]/div[2]/div[4]/mat-expansion-panel/div/div/div[2]/a[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-focus-indicator.button-sidebar-dropdown.mat-menu-item.user-feature-hide.is-user-available.is-checkable.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Mis fichajes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2b458cc-0e1b-4c9f-9aa7-72f7c06b4b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator button-sidebar-dropdown mat-menu-item user-feature-hide is-user-available is-checkable cdk-focused cdk-mouse-focused</value>
      <webElementGuid>0c352400-f4c2-469f-a0f5-ed97eccf67ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>332a9e9e-c7fd-40a7-80e6-8c2e1fc5e2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41df4e24-338d-48cc-9bdf-6d9febd482c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae168280-8ab6-4fe8-81a6-24687ff46567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/clock-hours</value>
      <webElementGuid>f910e952-6f52-48bf-bc79-50543ec7d376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mis fichajes</value>
      <webElementGuid>55f35531-c620-4454-81a2-bf580e9d06ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c160-7&quot;]/div[@class=&quot;sidebar-dropdown-wrapper ng-tns-c160-7&quot;]/a[@class=&quot;mat-focus-indicator button-sidebar-dropdown mat-menu-item user-feature-hide is-user-available is-checkable cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>8b5b6753-c4e0-4e4a-b269-d539609c32ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div[2]/a</value>
      <webElementGuid>3d363c73-d2a5-4663-aab8-5f12d8e647f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control horario'])[1]/following::a[1]</value>
      <webElementGuid>f077cbfd-0ae8-407b-9632-3b88df734c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestión interna'])[1]/following::a[1]</value>
      <webElementGuid>51c0caac-3b5c-4314-b85a-cf117b22824a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis ausencias'])[1]/preceding::a[1]</value>
      <webElementGuid>2afbb798-c1a7-414f-9214-ba63802ed5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/clock-hours')]</value>
      <webElementGuid>53656e80-a038-4ad7-85d6-7ac6cd1c99db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/mat-expansion-panel/div/div/div[2]/a</value>
      <webElementGuid>838cc0e2-473b-46f2-aad6-edbd237d7c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/clock-hours' and (text() = 'Mis fichajes' or . = 'Mis fichajes')]</value>
      <webElementGuid>afb61601-6330-4e04-a54c-cc7cc3a1f9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
