<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Entrada_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>c211c28c-3a56-44cd-b896-d0c9b817a016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyContainer']/roma-clock-hour/div/div/div/div/div[2]/button/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Entrada&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24de6c1a-79c5-4e0c-acb7-ce9b7587eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/icons/gl_play_v2.svg</value>
      <webElementGuid>d37aa851-19b0-4959-8118-4ebd7c1498d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>b963ed3d-ffb9-4561-9193-ba4125307419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyContainer&quot;)/roma-clock-hour[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;page-header&quot;]/div[@class=&quot;page-options&quot;]/div[@class=&quot;chronometer-container&quot;]/button[@class=&quot;roma-button pro-feature user-feature is-available is-checkable is-user-available&quot;]/img[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>fb3bd1f3-e214-438c-8230-6abb8c86b46f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/roma-clock-hour/div/div/div/div/div[2]/button/img[2]</value>
      <webElementGuid>df3da66f-452a-4958-bcee-9b61a284cf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/img[2]</value>
      <webElementGuid>ce263987-538f-4ac4-9a6c-d51c4d7e20fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/icons/gl_play_v2.svg']</value>
      <webElementGuid>de9f3dd0-ea0f-41dd-af94-b44c820d053b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
