<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar_1</name>
   <tag></tag>
   <elementGuidId>40bf9017-3b4c-47b7-bc87-4014efbc71db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.footer-button.delete-btn.user-feature.is-user-available.is-checkable.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Eliminar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fdd45b3a-2659-421b-ade3-abf486b431ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ffe21c5-5228-4bf4-a126-7a54b0bb649a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-button delete-btn user-feature is-user-available is-checkable ng-star-inserted</value>
      <webElementGuid>f690a4c4-0c97-4c4c-8929-d1977a45ef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Eliminar </value>
      <webElementGuid>64643669-b754-46cc-ad24-bcf15623bf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-4&quot;)/roma-create-final-v2[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal__body safe-area-padding&quot;]/div[@class=&quot;modal__body__content&quot;]/roma-final-wrapper-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper__body&quot;]/div[@class=&quot;wrapper__body__footer&quot;]/button[@class=&quot;footer-button delete-btn user-feature is-user-available is-checkable ng-star-inserted&quot;]</value>
      <webElementGuid>da84605b-cc15-4a17-acaf-b31591864b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>d0c2ad9b-02dc-456a-9a7e-c6bda109893f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-4']/roma-create-final-v2/div[2]/div[2]/roma-final-wrapper-detail/div/div[2]/button[2]</value>
      <webElementGuid>ea7090bd-e508-44ed-9561-19254f3ec13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar'])[1]/following::button[1]</value>
      <webElementGuid>07f09672-dee4-4064-887b-dc1b95c60db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campos personalizados'])[1]/following::button[2]</value>
      <webElementGuid>c920631b-646b-4496-963b-b21d32178e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archivos adjuntos'])[1]/preceding::button[1]</value>
      <webElementGuid>569f6fd2-c4c6-434d-874b-740ecf8118f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamaño máximo de archivo 10 MB'])[1]/preceding::button[1]</value>
      <webElementGuid>b0529c87-6018-4421-bde4-94b74624b33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roma-final-wrapper-detail/div/div[2]/button[2]</value>
      <webElementGuid>a1e6bfbd-389d-4f9c-b952-bb2fdb4ed595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Eliminar ' or . = ' Eliminar ')]</value>
      <webElementGuid>f2920076-96f7-4eb7-804a-6d285cafd436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
