<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customer_row</name>
   <tag></tag>
   <elementGuidId>838c45a0-2af9-43c6-827d-e983797d0820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='containerTable']/div/div/roma-table/div/div/div/mat-table/mat-row/mat-cell[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-cell.mat-cell.cdk-cell.mat-tooltip-trigger.cdk-column--------name_person.mat-column--------name_person.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;test&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-cell</value>
      <webElementGuid>61a2aaa5-0fb5-41be-9935-6641f4198cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>f8514f93-13d4-40f8-8d54-38078f5c7aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell mat-tooltip-trigger cdk-column--------name_person mat-column--------name_person ng-star-inserted</value>
      <webElementGuid>45535b54-8024-4063-a82e-d6085848c746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> test  </value>
      <webElementGuid>44d5992f-bf46-4a8b-85d7-d33d02bdc3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containerTable&quot;)/div[1]/div[@class=&quot;col-12&quot;]/roma-table[@class=&quot;table ng-star-inserted&quot;]/div[1]/div[@class=&quot;col-12&quot;]/div[@class=&quot;table-container&quot;]/mat-table[@class=&quot;mat-table cdk-table mat-sort&quot;]/mat-row[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell mat-tooltip-trigger cdk-column--------name_person mat-column--------name_person ng-star-inserted&quot;]</value>
      <webElementGuid>3a3aa778-fb80-4f39-a1ec-766e81243bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerTable']/div/div/roma-table/div/div/div/mat-table/mat-row/mat-cell[2]</value>
      <webElementGuid>5f6b555f-0d78-4062-bfb9-84b16d0e6ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[1]/following::mat-cell[2]</value>
      <webElementGuid>defeff9f-d332-425c-a801-853e532254b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test@test.com'])[1]/preceding::mat-cell[2]</value>
      <webElementGuid>83f24656-296b-4e1e-9d05-05b035540302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No disponible'])[1]/preceding::mat-cell[3]</value>
      <webElementGuid>8477fb75-955e-4d20-ad2d-3f6c4ff6d378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>7c03d50c-ea48-4a0a-bae1-fd9d3fa7f5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-cell[2]</value>
      <webElementGuid>4f06c287-3495-42e5-a81c-64fdae8e28bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-cell[(text() = ' test  ' or . = ' test  ')]</value>
      <webElementGuid>659c0e15-96a1-4d33-a778-aef0bb510e59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
