<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveTeamTracking</name>
   <tag></tag>
   <elementGuidId>c3c96c5c-3d3b-412f-b2bd-d1dabc75b872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[8]/div[2]/div/mat-dialog-container/roma-add-admin-clock-hour/roma-modal-template/div/div/div[3]/div/base-button/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
