<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TeamTraking</name>
   <tag></tag>
   <elementGuidId>3b41c380-561d-43f3-9be8-a4b789297551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/roma-root/roma-admin/div/div[1]/roma-sidebar/div[1]/div[2]/div[4]/mat-expansion-panel/div/div/div[2]/a[3]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
