<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sales_sidebar</name>
   <tag></tag>
   <elementGuidId>0f26f358-722a-4577-8691-14323f357a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/roma-root/roma-admin/div/div[1]/roma-sidebar/div[1]/div[2]/div[3]/mat-expansion-panel[1]/mat-expansion-panel-header/span/mat-panel-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
