<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar</name>
   <tag></tag>
   <elementGuidId>113ed8b7-0925-447f-a45b-c165a409fd9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/roma-add-admin-clock-hour/roma-modal-template/div/div/div[3]/div/base-button/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.primary.small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Guardar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6732dc7-7ddf-41a5-ab91-026fb0abf538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary small</value>
      <webElementGuid>83ac64db-7b01-4f3f-93e9-f76b16aa32d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Guardar </value>
      <webElementGuid>8c5ff613-257c-4d44-9ec1-fa98377ac9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/roma-add-admin-clock-hour[@class=&quot;ng-star-inserted&quot;]/roma-modal-template[1]/div[@class=&quot;safe-area-padding no-overflow-y&quot;]/div[@class=&quot;custom-modal custom-modal--mobile-full&quot;]/div[@class=&quot;modalFooter ng-star-inserted&quot;]/div[@class=&quot;groupEndDiv&quot;]/base-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;primary small&quot;]</value>
      <webElementGuid>16ea093c-6692-47a4-9cd2-310f44885486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/roma-add-admin-clock-hour/roma-modal-template/div/div/div[3]/div/base-button/button</value>
      <webElementGuid>ccaee73e-b2e4-4069-868a-f4e4ac16b5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir horas'])[1]/following::button[1]</value>
      <webElementGuid>83a20871-e530-4010-a140-06cf16145f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar']/parent::*</value>
      <webElementGuid>61aab619-649f-49f1-99a0-b5724d1e99df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//base-button/button</value>
      <webElementGuid>4fbf9cee-05c3-456c-b51f-36b2d12b5625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Guardar ' or . = ' Guardar ')]</value>
      <webElementGuid>add6631c-a953-44b5-bbe4-061228d86995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
