<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Aadir horas_endDate</name>
   <tag></tag>
   <elementGuidId>c6feccd1-21c4-4950-bbd5-ef1e644d012b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#endDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Introduzca la hora de salida&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33aed666-b632-4d09-b3ef-ffab970d9a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>c7add78c-c613-4dad-adba-68c36b18976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>endDateHelp</value>
      <webElementGuid>fc408993-9ca7-4797-a1d4-796ca2a42f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>6eb0831c-f430-453a-a435-41ec8c221fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>Hh:m0</value>
      <webElementGuid>33eaeab5-7f38-4ddc-97f8-0b23458b89f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3fa4a6a5-2a6d-4a2d-a7ed-5750459bdb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Introduzca la hora de salida</value>
      <webElementGuid>b5b3d0ff-792f-4ee8-bdba-2ba287400326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDate&quot;)</value>
      <webElementGuid>c9cbc17e-9b99-42f6-9f2b-a7775a902d8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endDate']</value>
      <webElementGuid>dd04a1fc-86e1-4943-9ff2-3d718d4c3511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/roma-add-admin-clock-hour/roma-modal-template/div/div/div[2]/form/roma-add-time/form/div[2]/div[2]/input</value>
      <webElementGuid>b94befd7-0e9c-4ed3-be57-2b8d09478e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>65bf0a25-3b97-4c50-a989-2aba96120fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'endDate' and @placeholder = 'Introduzca la hora de salida']</value>
      <webElementGuid>3f1920d3-da44-42f7-b0ab-4082b4926b43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
