<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reservas Online</name>
   <tag></tag>
   <elementGuidId>26c2cade-a767-45cc-b0c7-d8759d7d1bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-focus-indicator.button-sidebar.mat-button.mat-button-base.user-feature-hide.is-user-available.is-checkable.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes de Trabajos'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Reservas Online Reservas Online&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39cd0ff5-a1a1-47dc-981f-aca519c2d3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator button-sidebar mat-button mat-button-base user-feature-hide is-user-available is-checkable ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>1014c73a-47e4-488e-a3af-1535a17cd4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a4508f1a-6788-43c7-a2ba-cfa736713734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff0f1516-3073-466b-b70f-b1aa4994e8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/online-booking</value>
      <webElementGuid>f089b5e7-b4c0-4b65-94ef-2872b4a783f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservas Online</value>
      <webElementGuid>9e56e774-811b-42c2-a914-7d9e94d28d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/roma-root[1]/roma-admin[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;site&quot;]/div[@class=&quot;sidebar-container ng-star-inserted&quot;]/roma-sidebar[@class=&quot;roma-sidebar ng-star-inserted&quot;]/div[@class=&quot;desktop-sidebar&quot;]/div[@class=&quot;desktop-sidebar-body no-improve&quot;]/div[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;mat-focus-indicator button-sidebar mat-button mat-button-base user-feature-hide is-user-available is-checkable ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>f8034d72-dba6-40ae-88c0-c6ee7914be72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes de Trabajos'])[1]/following::a[1]</value>
      <webElementGuid>fec342f6-40ec-4188-b2d1-875ddc72b872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes'])[2]/following::a[2]</value>
      <webElementGuid>91f41c13-fbca-4988-ba38-8ac9f5140126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::a[1]</value>
      <webElementGuid>03f6ebd2-18f7-47ee-94f7-e783c830465b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/online-booking')]</value>
      <webElementGuid>c643f9d5-5543-4379-bab1-19d308207807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>598009f8-dd6e-490b-b548-39376fbae029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/online-booking' and (text() = 'Reservas Online' or . = 'Reservas Online')]</value>
      <webElementGuid>8e808803-6296-4fad-beee-8c4c3a00bae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
