<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_24</name>
   <tag></tag>
   <elementGuidId>3f4a66ef-495c-457a-8b9e-99b2adaba0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;24&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfb9abae-e4d0-4849-84dd-b582aee0a03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d55c428d-bfb1-433c-9956-5da4e2ab671c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100</value>
      <webElementGuid>804feb6c-8e8a-4a24-bf33-201c02ff2f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3335efda-d797-430f-8e06-1020281bc2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-1/2 w-full&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative !rounded-lg border border-primary-100 h-11&quot;]/div[@class=&quot;!h-11 !rounded-full !outline-transparent cursor-pointer&quot;]/div[@class=&quot;absolute z-50 mt-3 dark:bg-white&quot;]/div[@class=&quot;inline-block rounded-lg bg-white p-4 shadow-lg dark:bg-white&quot;&quot;]/div[@class=&quot;p-1&quot;]/div[@class=&quot;grid w-64 grid-cols-7&quot;]/button[@class=&quot;w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100&quot;]</value>
      <webElementGuid>bcf4b78e-a909-48ff-84f7-384b81dfb5e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>966a48c3-ec13-43b6-b969-1fea20367d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/button[24]</value>
      <webElementGuid>9d3173fc-1bbe-4c68-9cfe-7b395a990557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dom'])[1]/following::button[24]</value>
      <webElementGuid>a498115c-ba45-4620-a122-a05045919dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb'])[1]/following::button[24]</value>
      <webElementGuid>10c3b749-d2b7-4f01-bfad-252bab2ce12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoy'])[1]/preceding::button[19]</value>
      <webElementGuid>62723c4c-3caf-400f-8d6c-3a7f7a21b05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desde *'])[1]/preceding::button[20]</value>
      <webElementGuid>d19c5f7b-e6c3-491a-93e9-c6ef0bfe5397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24']/parent::*</value>
      <webElementGuid>550ac80e-974b-4ad7-a0f5-c50a924af152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[24]</value>
      <webElementGuid>12e6eeb9-8c3b-4b96-8a5b-eebfd0880e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '24' or . = '24')]</value>
      <webElementGuid>b7fd0eb1-922d-4d4c-8c5d-8a72fa93d0e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
