<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_3</name>
   <tag></tag>
   <elementGuidId>61d39cbd-e821-4cfc-87db-4bbb52e6d972</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;3&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcf52793-0656-445c-be5c-001c8881d349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9ac9be6-764f-49a4-8af3-778d12a8d7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100</value>
      <webElementGuid>f02c0765-fdf0-423e-84f3-8abe6278f57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6411888a-72c7-4d33-ac32-3a8324704e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-1/2 w-full&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative !rounded-lg border border-primary-100 h-11&quot;]/div[@class=&quot;!h-11 !rounded-full !outline-transparent cursor-pointer&quot;]/div[@class=&quot;absolute z-50 mt-3 dark:bg-white&quot;]/div[@class=&quot;inline-block rounded-lg bg-white p-4 shadow-lg dark:bg-white&quot;&quot;]/div[@class=&quot;p-1&quot;]/div[@class=&quot;grid w-64 grid-cols-7&quot;]/button[@class=&quot;w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100&quot;]</value>
      <webElementGuid>bb28f0a1-41ac-418e-bd59-441cc37ec26e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>1058b521-280f-41f2-98f2-567b8c0915d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/button[3]</value>
      <webElementGuid>480f0383-d741-4674-b41b-e7c81896b413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dom'])[1]/following::button[3]</value>
      <webElementGuid>0a381ce8-834b-4e9f-85e6-47fe733dfbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb'])[1]/following::button[3]</value>
      <webElementGuid>d7d1ea32-690c-4b34-8843-11895375c2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoy'])[1]/preceding::button[40]</value>
      <webElementGuid>01d5be75-8f10-4c0d-90d9-56c65812d80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desde *'])[1]/preceding::button[41]</value>
      <webElementGuid>0113e143-05b9-4c98-9e30-fdf181c41b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>1b5377b6-9be4-4842-9898-4fdce7f44910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button[3]</value>
      <webElementGuid>f1113863-f8b8-48ae-9276-54204e1dbbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '3' or . = '3')]</value>
      <webElementGuid>504b03c6-7bab-45ae-9d5f-a803fe3662a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
