<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_30</name>
   <tag></tag>
   <elementGuidId>d21034d9-6a14-40ac-b401-54bcab95bdff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[40]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;30&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc13d999-1b26-4eca-a05f-33356900008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f0293f5-0c34-4281-a4d8-ac2c4e16cc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100</value>
      <webElementGuid>bfe2ed3b-d224-40d8-af77-f2afbc64850b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>613ee33a-510f-43ba-93c8-d03f7b31982b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-1/2 w-full&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative !rounded-lg border border-primary-100 h-11&quot;]/div[@class=&quot;!h-11 !rounded-full !outline-transparent cursor-pointer&quot;]/div[@class=&quot;absolute z-50 mt-3 dark:bg-white&quot;]/div[@class=&quot;inline-block rounded-lg bg-white p-4 shadow-lg dark:bg-white&quot;&quot;]/div[@class=&quot;p-1&quot;]/div[@class=&quot;grid w-64 grid-cols-7&quot;]/button[@class=&quot;w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100&quot;]</value>
      <webElementGuid>bdd8b761-cb3a-40e8-b010-2d89a3169d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[40]</value>
      <webElementGuid>bd1bcb61-4f06-4311-89c6-be5c13e638fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/button[30]</value>
      <webElementGuid>dc04f244-6ce0-4f62-a2f6-d15ff3831920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dom'])[1]/following::button[30]</value>
      <webElementGuid>a30a21f6-bb03-43c2-bf0a-82c46616a857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb'])[1]/following::button[30]</value>
      <webElementGuid>78904d02-76f3-4f6c-865c-62375a547241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoy'])[1]/preceding::button[13]</value>
      <webElementGuid>e927599b-b874-40ac-8192-a8aea68366c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desde *'])[1]/preceding::button[14]</value>
      <webElementGuid>6758c29e-45fe-4e02-83b7-066ce1520d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30']/parent::*</value>
      <webElementGuid>58a82266-e9d7-4ee0-bb76-904c2b89b6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[30]</value>
      <webElementGuid>94ef28b1-03c8-43bc-a755-032aadc5bc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '30' or . = '30')]</value>
      <webElementGuid>1c94a188-5f4b-4f28-91d6-a5f927a02e10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
