<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_day</name>
   <tag></tag>
   <elementGuidId>011260ae-0194-4e54-99ac-7287ab03ee79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[28]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;18&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4414e95c-b9aa-486c-9ce4-18178fdd2060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d389c80-83ba-4d60-91b4-1b3b00172a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100</value>
      <webElementGuid>ef1fd77f-529a-49fb-8344-138557158d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e7517151-1952-4a3b-9b6b-8ecadf5afbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-1/2 w-full&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative !rounded-lg border border-primary-100 h-11&quot;]/div[@class=&quot;!h-11 !rounded-full !outline-transparent cursor-pointer&quot;]/div[@class=&quot;absolute z-50 mt-3 dark:bg-white&quot;]/div[@class=&quot;inline-block rounded-lg bg-white p-4 shadow-lg dark:bg-white&quot;&quot;]/div[@class=&quot;p-1&quot;]/div[@class=&quot;grid w-64 grid-cols-7&quot;]/button[@class=&quot;w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100&quot;]</value>
      <webElementGuid>a7d8fef3-35f3-4217-a2b8-e3bbf9f8704b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[28]</value>
      <webElementGuid>ecd3e185-f1cb-410f-bd32-d9a1dc080161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/button[18]</value>
      <webElementGuid>42b844de-0c1d-4653-910f-184cc76cf619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dom'])[1]/following::button[18]</value>
      <webElementGuid>4996c30c-6f4c-4dc7-831e-7e3bdfc3f06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb'])[1]/following::button[18]</value>
      <webElementGuid>b5dc4cb1-3c3e-437e-aba2-6317f95e32e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoy'])[1]/preceding::button[25]</value>
      <webElementGuid>18daede2-f82c-499f-bbbc-c2f08356087b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desde *'])[1]/preceding::button[26]</value>
      <webElementGuid>c892d4ec-6b5f-4b8e-a986-7dc835866a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='18']/parent::*</value>
      <webElementGuid>06c32ae3-c4b6-44fb-a27e-989f085b0076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[18]</value>
      <webElementGuid>41affcf2-365a-488d-997f-4a52ef046152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '18' or . = '18')]</value>
      <webElementGuid>021304de-5a1d-4264-917e-6e54dd289694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
