<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_today</name>
   <tag></tag>
   <elementGuidId>6e3d7195-48ab-4156-ae39-ca5aa46f4cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[39]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;29&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0ea648c-bfd8-49c6-b505-7c4a9a4851bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bb0c92e-aecd-42ef-8907-4e943633b70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100 bg-primary text-white</value>
      <webElementGuid>cbb8b4c8-e2c2-4367-b193-7850a15b7ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>ac4af2ff-072c-4a33-8b86-4388c6ec1505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-1/2 w-full&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative !rounded-lg border border-primary-100 h-11&quot;]/div[@class=&quot;!h-11 !rounded-full !outline-transparent cursor-pointer&quot;]/div[@class=&quot;absolute z-50 mt-3 dark:bg-white&quot;]/div[@class=&quot;inline-block rounded-lg bg-white p-4 shadow-lg dark:bg-white&quot;&quot;]/div[@class=&quot;p-1&quot;]/div[@class=&quot;grid w-64 grid-cols-7&quot;]/button[@class=&quot;w-9 h-9 !m-[1px] text-xs text-center font-regular rounded-full flex items-center justify-center hover:bg-primary-100 bg-primary text-white&quot;]</value>
      <webElementGuid>81731057-c8af-4c83-8bad-b61c3eaa033d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[39]</value>
      <webElementGuid>51300305-ea6f-4ff3-ab82-91c9b39b2cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/button[29]</value>
      <webElementGuid>57308c4c-9218-43ad-8fa3-ff3b6d94168b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dom'])[1]/following::button[29]</value>
      <webElementGuid>d49f6842-c999-42e0-aad7-5984ae343ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sáb'])[1]/following::button[29]</value>
      <webElementGuid>c94c5d27-4799-4561-88ef-4ee09bbd8ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoy'])[1]/preceding::button[14]</value>
      <webElementGuid>dc8d853a-cca0-4353-995c-f877dff6c939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desde *'])[1]/preceding::button[15]</value>
      <webElementGuid>29589b16-c6de-466d-ae5c-a8f7501129c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='29']/parent::*</value>
      <webElementGuid>ad227174-dc77-4961-837d-562e322dbe9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[29]</value>
      <webElementGuid>bae89588-062a-4982-be66-a92d67f9616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '29' or . = '29')]</value>
      <webElementGuid>6107d225-b048-4fdd-aa10-4f1431ce90cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
