<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Razn_reason</name>
   <tag></tag>
   <elementGuidId>564b44a6-370b-4899-b52a-b7d7cf0e2480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;reason&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fad49c7f-e34a-45f3-a9f3-709571c0514f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a6195ec-c70b-4cef-80fb-3137838cf195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ej: Enfermedad / Festivo</value>
      <webElementGuid>82d03c06-50f3-4eb6-bfb7-f7219411f5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>92fcd6c3-c8c5-4e66-9b39-7a2d2e9aa3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>reason</value>
      <webElementGuid>c0bb7c13-b7b9-43c9-9602-e300c6f5d6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 border-[#F73949]</value>
      <webElementGuid>08197c02-f653-43ea-9163-96e8b5699151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reason&quot;)</value>
      <webElementGuid>425ba628-4014-4e2a-bd6b-dad3cf842772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reason']</value>
      <webElementGuid>93187ce8-4d60-436d-a5be-20156f8eb437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div/div/div[2]/input</value>
      <webElementGuid>827a5c7d-a532-4347-8b87-a29e3a8083da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/input</value>
      <webElementGuid>8c458db2-427d-4003-941b-cf28978bf2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Ej: Enfermedad / Festivo' and @id = 'reason']</value>
      <webElementGuid>f6aeec56-6266-4ac1-b253-5e75e0edca5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
