<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Desde_hour-input</name>
   <tag></tag>
   <elementGuidId>9d02351c-2444-4965-b172-eed9a8bb639e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='hour-input'])[17]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-2/5 w-full flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-row gap-4 -mb-3 w-full relative mb-5&quot;]/div[@class=&quot;w-1/2 flex flex-col&quot;]/div[1]/div[@class=&quot;relative&quot;]/input[@id=&quot;hour-input&quot;][count(. | //input[@type = 'text' and @placeholder = '--:--' and @id = 'hour-input' and @data-testid = 'hour-input' and @class = 'font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 !text-center !w-[68px] h-10 md:!h-10 !pl-3 !pr-3 !py-1 md:!w-24 md:px-6 md:py-2  text-start border-primary-100']) = count(//input[@type = 'text' and @placeholder = '--:--' and @id = 'hour-input' and @data-testid = 'hour-input' and @class = 'font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 !text-center !w-[68px] h-10 md:!h-10 !pl-3 !pr-3 !py-1 md:!w-24 md:px-6 md:py-2  text-start border-primary-100'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Desde \*$/ >> [data-testid=&quot;hour-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c086575a-4432-4478-a0fb-f5a989917477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>736ba92c-5d89-4739-a165-b65cadeaf403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--:--</value>
      <webElementGuid>074eaca3-4b8b-49b0-b371-d27310e35fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hour-input</value>
      <webElementGuid>d4a88ade-4e90-4c54-b55f-e1bcccc03ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>hour-input</value>
      <webElementGuid>3f069dd2-049d-4519-a437-5eba37fc03a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 !text-center !w-[68px] h-10 md:!h-10 !pl-3 !pr-3 !py-1 md:!w-24 md:px-6 md:py-2  text-start border-primary-100</value>
      <webElementGuid>93d9ebbc-3099-412c-a15d-b1955e73a3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-2/5 w-full flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-row gap-4 -mb-3 w-full relative mb-5&quot;]/div[@class=&quot;w-1/2 flex flex-col&quot;]/div[1]/div[@class=&quot;relative&quot;]/input[@id=&quot;hour-input&quot;]</value>
      <webElementGuid>20d71527-95c7-4bab-af9d-9716a5c21c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='hour-input'])[17]</value>
      <webElementGuid>556d2686-8c9b-456e-b2a1-88e084e6fecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>697386bd-341e-436c-8d16-830d6ff2473e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>a51749cf-3bdb-4119-944a-be311024ab1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '--:--' and @id = 'hour-input']</value>
      <webElementGuid>39b7c922-4aad-40e2-a94a-ee0528c2991c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
