<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha_datepicker-2</name>
   <tag></tag>
   <elementGuidId>cc906ab8-e5f8-4d78-92c4-5b647fe6345e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepicker-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepicker-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;datepicker-2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c04d6de-4bb0-4085-8e24-c815df5ae743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!px-4 !py-1 relative cursor-pointer font-regular w-full h-full !outline-none placeholder:font-regular placeholder:text-gray-3 disabled:!text-gray-3 border-gray-300 text-gray-900 focus:border-cyan-500 focus:ring-cyan-500 p-2.5 text-sm rounded-lg</value>
      <webElementGuid>8e797b32-e7da-4ca2-95db-8c0ed0a4b48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b398005e-20b1-4b2f-8a79-a711f1df31d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepicker-2</value>
      <webElementGuid>be6a7253-c9c3-402d-b5cb-d214cf2e267d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--/--/----</value>
      <webElementGuid>6a8e9331-1058-4763-aae7-1a165e6474e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>datepicker-2</value>
      <webElementGuid>e690aa12-7f6e-49ee-bc7b-d3c26803b4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>29/07/2024</value>
      <webElementGuid>b1ed00ae-1994-453d-9550-c2c069f6cf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-2&quot;)</value>
      <webElementGuid>c3326409-ce1a-469b-8650-18c5f369c74f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepicker-2']</value>
      <webElementGuid>975d43ca-e9cc-4505-9338-026e46d4659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>2ef79372-d03c-45c3-8468-d5758ce228db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>7380dab2-0f33-4a14-9736-f480f5f3bde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'datepicker-2' and @placeholder = '--/--/----']</value>
      <webElementGuid>e03baf4a-c6ba-4c6e-961c-151c1593c157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
