<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hasta_hour-input</name>
   <tag></tag>
   <elementGuidId>3b47405c-7f77-4071-b911-ef64e7828a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='hour-input'])[18]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Hasta \*$/ >> [data-testid=&quot;hour-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf31f64b-4c66-4c41-b738-ceb3f657a80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2c70a62-abc3-4440-a099-1f4f682d8af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--:--</value>
      <webElementGuid>c5f30351-3c44-4a07-8bf1-3fae87107972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hour-input</value>
      <webElementGuid>b785a10b-1169-4a60-a688-cd3a1d64780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>hour-input</value>
      <webElementGuid>a2f4564c-4036-4a89-a75e-840b54abfe2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-regular pr-4 py-3 bg-white text-sm resize-none rounded-lg border !ring-transparent !outline-none placeholder:text-[#8C9DD2] w-full h-11 !text-center !w-[68px] h-10 md:!h-10 !pl-3 !pr-3 !py-1 md:!w-24 md:px-6 md:py-2  text-start border-primary-100</value>
      <webElementGuid>efe0e045-8fd6-40cb-8540-c7da48131b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rc:&quot;)/div[@id=&quot;block-schedule-modal&quot;]/div[@id=&quot;block-schedule-modal&quot;]/div[@class=&quot;relative md:rounded-3xl rounded-none bg-white&quot;]/div[@class=&quot;md:px-10 md:pt-6 md:pb-8 px-6 py-4 h-screen md:h-auto&quot;]/div[@class=&quot;flex-1 overflow-visible p-0 w-full&quot;]/form[1]/div[@class=&quot;w-full flex md:flex-row flex-col gap-4 mt-7&quot;]/div[@class=&quot;md:w-2/5 w-full flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-row gap-4 -mb-3 w-full relative mb-5&quot;]/div[@class=&quot;w-1/2 flex flex-col&quot;]/div[1]/div[@class=&quot;relative&quot;]/input[@id=&quot;hour-input&quot;]</value>
      <webElementGuid>7747a3e8-9854-4473-aa83-01b9ab397b5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='hour-input'])[18]</value>
      <webElementGuid>6be3b093-03ac-433f-a445-70246913883f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-schedule-modal']/div/div/div[2]/form/div[2]/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>12dcdb95-f915-4b7b-beca-b343f164569a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>b397218f-27fc-4523-b80a-27952a1c2ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '--:--' and @id = 'hour-input']</value>
      <webElementGuid>f22bce59-5d71-4b14-8d05-1b7e589e42fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
